# Generated by Django 4.1.6 on 2023-03-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(
                blank=True, help_text="Required, please enter a date", null=True
            ),
        ),
    ]
