# Generated by Django 4.1.6 on 2023-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_management", "0006_notification_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
