# Generated by Django 4.1.6 on 2023-07-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_management", "0008_alter_photo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
