# Generated by Django 4.1.6 on 2023-07-21 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_management", "0009_photo_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="name",
        ),
    ]
