version: '3.8'

services:
  web:
    build: ./peer_mentoring
    command: daphne -b 0.0.0.0 -p 8000 peer_mentoring.asgi:application
    volumes:
      - ./peer_mentoring/:/usr/src/peer_mentoring/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
