# Generated by Django 4.1.6 on 2023-03-02 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, unique=True, upload_to="interests"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="photos")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("dob", models.DateField(help_text="Required, please enter a date")),
                (
                    "avatar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_management.photo",
                    ),
                ),
                ("interests", models.ManyToManyField(to="account_management.interest")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
