# Generated by Django 4.1.6 on 2023-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_management", "0004_userprofile_groups_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="groups_joined",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, to="account_management.userprofile"
            ),
        ),
    ]
