# Use an official Python runtime as the base image
FROM python:3

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Copy the requirements file to the container
COPY requirements.txt /code/

# Install the project dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Django server port
EXPOSE 8000

# Copy the project code to the container
COPY . /code/

# Start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
