version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: peer_mentoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:6

  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

volumes:
  db_data:
