# Generated by Django 4.1.6 on 2023-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_group_post",
            field=models.BooleanField(default=True),
        ),
    ]
