# Generated by Django 4.1.6 on 2023-03-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_rename_comments_comment_post_group_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="is_group_post",
            new_name="group",
        ),
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
            preserve_default=False,
        ),
    ]
