# Generated by Django 4.1.6 on 2023-03-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_remove_group_members"),
        ("posts", "0004_rename_is_group_post_post_group_remove_post_comments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="group_id",
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.group",
            ),
        ),
    ]
