# Generated by Django 4.1.6 on 2023-03-24 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_remove_post_group_id_alter_post_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="group",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
