# Generated by Django 4.1.6 on 2023-03-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="avatar")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(max_length=250)),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "avatar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="groups.avatar"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(to="account_management.userprofile"),
                ),
            ],
        ),
    ]
