# Generated by Django 4.1.6 on 2023-03-15 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
    ]
