# Generated by Django 4.1.6 on 2023-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_group_category_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
