# Generated by Django 4.1.6 on 2023-03-24 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="category",
        ),
    ]
