# Generated by Django 4.1.6 on 2023-03-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0005_remove_group_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="category",
            field=models.ForeignKey(
                default="test",
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.category",
            ),
        ),
    ]
