# Generated by Django 4.1.6 on 2023-05-04 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0006_group_member_alter_group_moderator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="member",
            new_name="members",
        ),
    ]
