# Generated by Django 4.1.6 on 2023-05-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_management", "0006_notification_friendrequest"),
        ("groups", "0008_groupjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupjoinrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupjoinrequest",
            name="receiver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_received_requests",
                to="account_management.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="groupjoinrequest",
            name="sender",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_sent_requests",
                to="account_management.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="groupjoinrequest",
            unique_together={("sender", "receiver")},
        ),
        migrations.RemoveField(
            model_name="groupjoinrequest",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="groupjoinrequest",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupjoinrequest",
            name="user",
        ),
    ]
