# Generated by Django 4.1.6 on 2023-05-19 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0010_groupjoinrequest_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupjoinrequest",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_received_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupjoinrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_sent_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
