# Generated by Django 4.1.6 on 2023-05-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0005_group_moderator"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="member",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="group",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
