# Generated by Django 4.1.6 on 2023-06-10 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0013_alter_group_banned_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-added",)},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-added",)},
        ),
        migrations.AlterField(
            model_name="group",
            name="banned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="banned_from_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
