# Generated by Django 4.1.6 on 2023-06-21 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_privatechatmessage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="privatechatmessage",
            unique_together={("sender", "receiver")},
        ),
    ]
