# Generated by Django 4.1.6 on 2023-06-26 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_privatechatmessage_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="privatechatmessage",
            unique_together=set(),
        ),
    ]
